#
# BUILD STAGE
#
FROM maven:latest AS BUILDER
COPY . /builder
WORKDIR /builder
RUN mvn clean install -DskipTests=false

#
# PACKAGE STAGE
#
FROM openjdk:17-jdk-slim AS RUNNER
COPY --from=BUILDER /builder/target/*.jar /app/app.jar
WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
