name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  release:
    types: [ created ]

jobs:
  test_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/.github # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B package -s $GITHUB_WORKSPACE/.github/settings.xml --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  publish_build:
    runs-on: ubuntu-latest
    needs: [test_build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/.github # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B package -s $GITHUB_WORKSPACE/.github/settings.xml --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/.github/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
